# Cloudflare Tunnel Configuration for IBKR Broker Service
# 
# INSTRUCTIONS:
# 1. Replace YOUR_TUNNEL_NAME with your tunnel name (e.g., ibkr-broker)
# 2. Replace YOUR_USERNAME with your Mac username (e.g., kevin)
# 3. Replace YOUR_TUNNEL_ID with the UUID from ~/.cloudflared/*.json
# 4. Replace yourdomain.com with your actual domain
# 5. Copy this to ~/.cloudflared/config.yml

tunnel: YOUR_TUNNEL_NAME
credentials-file: /Users/YOUR_USERNAME/.cloudflared/YOUR_TUNNEL_ID.json

ingress:
  # Route traffic from your domain to the local IBKR broker service
  - hostname: ibkr-broker.yourdomain.com
    service: http://127.0.0.1:8081
  
  # Catch-all rule (required)
  - service: http_status:404

# Optional: Enable logging
# logfile: /Users/YOUR_USERNAME/.cloudflared/tunnel.log
# loglevel: info

